### ISSUE TITLE
Nutanix CSI operator disconnected install issue

### ISSUE THREAD

**Issue by pbertera** [redhat-openshift-ecosystem/certified-operators#1514]
The Nutanix CSI operator defines various images that are not mentioned into the operator CSV.
For that reason tools like `oc mirror` or `oc adm mirror` fails to locally download those image and creating the related `ImageContentSourcePolicy`.

- Nutanix CSI Helm charts: https://github.com/nutanix/helm/blob/master/charts/nutanix-csi-storage/values.yaml#L122-L145
- `nutanix-csi-operator` images:
```
$ podman run -it --entrypoint '/bin/sh' registry.connect.redhat.com/nutanix/nutanix-csi-operator@sha256:fbb5204d196f84b2b38278ae411b1a2fa63919a194febe333fe5ed932b3a328f -c "grep image: helm-charts/nutanix-csi-storage/values.yaml"
  image: registry.connect.redhat.com/nutanix/ntnx-csi-os@sha256:66693da887ba2d9388aff5c4459a16a717246127c07bebdf36c573095a3e2118
  image: registry.connect.redhat.com/nutanix/ntnx-csi-os@sha256:66693da887ba2d9388aff5c4459a16a717246127c07bebdf36c573095a3e2118
    image: k8s.gcr.io/sig-storage/csi-node-driver-registrar@sha256:0103eee7c35e3e0b5cd8cdca9850dc71c793cdeb6669d8be7a89440da2d06ae4
    image: k8s.gcr.io/sig-storage/csi-provisioner@sha256:8027dd89dfd93741e06afced6ab6d6862dcb2a4b21f90070ae5802f46a894534
    image: k8s.gcr.io/sig-storage/csi-snapshotter@sha256:ad16874e2140256a809cada2b4ac3d931d5b73b0bee23ed0f8d60bdd778cfec2
    image: k8s.gcr.io/sig-storage/csi-resizer@sha256:8f7520bd957e7151fda9886eb5090739439811aeec5ddffb50ad7c8191548d97
    image: k8s.gcr.io/sig-storage/livenessprobe@sha256:933940f13b3ea0abc62e656c1aa5c5b47c04b15d71250413a6b821bd0c58b94e
```
- Operator CSV's `relatedImages`: https://github.com/redhat-openshift-ecosystem/certified-operators/blob/main/operators/nutanixcsioperator/2.5.4/manifests/nutanixcsioperator.clusterserviceversion.yaml#L327-L333

**Comment by pbertera** [comment]
@tuxtof I see a new version of the operator with a more comprehensive list of `relatedImages`[1], will the new version supposed to fix this issue?
If so I'll close it.

[1] https://github.com/redhat-openshift-ecosystem/certified-operators/blob/main/operators/nutanixcsioperator/2.6.1/manifests/nutanixcsioperator.clusterserviceversion.yaml#L345-L373

**Comment by tuxtof** [comment]
Yes it is fixed

**Comment by pbertera** [comment]
Thanks, I'm closing the issue then.
