### ISSUE TITLE
Can I create a new PR for an existing operator version after it has passed through the pipeline

### ISSUE THREAD

**Issue by turbodeploy** [redhat-openshift-ecosystem/certified-operators#2226]
I had a PR, https://github.com/redhat-openshift-ecosystem/certified-operators/pull/2207 that was successful and published.  I have noticed I have a mistake in the clusterserviceversion.yaml, line 205:
 replaces: t8c-operator.v42.28.0

This should be 42.29.0, so it is a mistake.  Can I just open up a new PR and have it update the released bundle?

**Comment by Allda** [comment]
Hi @turbodeploy the policy for certified operators doesn't allow to update existing operators that have been already released. You can always release a new version and use replaces and skipRange to control your upgrader graph path.

However, we are going to introduce a File-based catalog soon which will allow you to modify your catalog in a more granular and user-friendly way.
