### ISSUE TITLE
Release pipeline hangs/stops at acquire-lease step after merging

### ISSUE THREAD

**Issue by adwk67** [redhat-openshift-ecosystem/certified-operators#2245]
PR https://github.com/redhat-openshift-ecosystem/certified-operators/pull/2242 has been merged but stops/hangs at the acquire-lease step, meaning that the operator does not appear under the list of certified operators.

**Comment by Allda** [comment]
I see the PR was manually retriggered and the operator has been released. We recently added a new feature that allows users to restart a pipeline in case of failure. Next time when this happens you will be able to restart a pipeline by yourself.
