### ISSUE TITLE
cannot create pull request due to submission-validation failure

### ISSUE THREAD

**Issue by kasserater** [redhat-openshift-ecosystem/certified-operators#3160]
i cannot submit a PR due to submission-validation failure
i have asked for permissions on the slack channel #cloudpak-redhat-certification but did not see any progress and this is an urgent need to resolve a customer issue

**Comment by Allda** [comment]
@kasserater Hey, I see you were able to submit your operator successfully: https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3211

Do you need any further assistance or can this issue be closed?

**Comment by kasserater** [comment]
Indeed we resolved this issue.
Issue can be closed

All the best,
Ariel
________________________________
From: Aleš Raszka ***@***.***>
Sent: Thursday, December 21, 2023 4:32:29 PM
To: redhat-openshift-ecosystem/certified-operators ***@***.***>
Cc: Ariel Kass ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [redhat-openshift-ecosystem/certified-operators] cannot create pull request due to submission-validation failure (Issue #3160)

@kasserater Hey, I see you were able to submit your operator successfully: #3211 Do you need any further assistance or can this issue be closed? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!1a-piBT0QJEZEc2xc0kuhSF6_NZr5MqTAtNnlIg_JqcMRQrdT5c_oQkGs4YomDMWUli2AFKECEvtEDI5htl5A_2HTZcg-VWnWVecJiBYipQaM_0J_rbm1VZ_fx9aWoCr7sTuJJhkR_V4$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

@kasserater<https://github.com/kasserater> Hey, I see you were able to submit your operator successfully: #3211<https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3211>

Do you need any further assistance or can this issue be closed?
