### ISSUE TITLE
Confluent-for-kubernetes versions shipped on 4.6 to 4.9 only works on 4.9

### ISSUE THREAD

**Issue by camilamacedo86** [redhat-openshift-ecosystem/certified-operators#552]
**Problem**

Both bundles only work on OCP versions >= 4.9 because their size is bigger than > 1MB: 

- confluent-for-kubernetes.v2.1.1 ( skipRange >=2.0.3 <2.1.1  - channel:  2.1 )
- confluent-for-kubernetes.v2.2.1 ( no upgrade graph config - first bundle published for this channel / chanel: stable) 

See in 4.8:

<img width="624" alt="Screenshot 2022-02-25 at 08 24 12" src="https://user-images.githubusercontent.com/7708031/155707247-d3602a16-07f2-4aa5-8d61-230dc6ffc5be.png">

```
time="2022-02-24T12:04:13Z" level=info msg="Using in-cluster kube client config"
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/confluent-for-kubernetes.clusterserviceversion.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/confluent-operator-licensing_v1_secret.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/confluent-operator-service_v1_service.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/platform.confluent.io_confluentrolebindings.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/platform.confluent.io_connectors.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/platform.confluent.io_connects.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/platform.confluent.io_controlcenters.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/platform.confluent.io_kafkarestclasses.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/platform.confluent.io_kafkarestproxies.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/platform.confluent.io_kafkas.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/platform.confluent.io_kafkatopics.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/platform.confluent.io_ksqldbs.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/platform.confluent.io_migrationjobs.yaml
time="2022-02-24T12:04:13Z" level=info msg="Reading file" file=/bundle/manifests/platform.confluent.io_schemaregistries.yaml
time="2022-02-24T12:04:13Z" level=error msg="File with size 130712 exceeded 1048576 limit, aboring" file=/bundle/manifests/platform.confluent.io_schemaregistries.yaml
Error: error loading manifests from directory: file platform.confluent.io_schemaregistries.yaml bigger than total allowed limit
Usage:
  opm alpha bundle extract [flags]
```

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2054514

**Questions**

a) Would it be possible to allow us to update the OCP labels by pushing a PR to replace `"v4.6-v4.9"` with `"=v4.9"` for we have these solutions published only in 4.9? 
- https://github.com/redhat-openshift-ecosystem/certified-operators/blob/main/operators/confluent-for-kubernetes/2.2.1/metadata/annotations.yaml#L10
- https://github.com/redhat-openshift-ecosystem/certified-operators/blob/main/operators/confluent-for-kubernetes/2.2.0/metadata/annotations.yaml#L10

So that, we could ensure that these bundles are not published in OCP catalogs where them does not work at all. 

b) Would be possible afterwards: 

- Push another PR with these both dirs `2.2.1` and `2.2.0` like as `2.2.1.v4.6_v4.8` and `2.2.0.v4.6_v4.8`
- Then, ensure that  `2.2.1.v4.6_v4.8` and `2.2.0.v4.6_v4.8` are < ~1MB
- Keep them with the identical versions, names, etc. and with the OCP label   `"v4.6-v4.8"`

So that, we can have smaller workable bundle versions (< 1MB) that would end up only 4.6, 4.7, 4.8 only? 

OR

c)  Would be a better approach:

- replace both bundles with smaller versions < (~1MB) 
- keep the OCP label `v4.6-v4.9` 
- and then, afterwards, if we want to have bigger bundles > (~1MB), publish the next/future ones with OCP label ranges that will be valid from 4.9 to avoid the same scenario occurring? 

So that, we do not have the directories duplicated here (maybe easier to keep maintained), we can still work with bundles > ~1MB and release them from 4.9 only.

**Comment by camilamacedo86** [comment]
c/c @amitkgupta

**Comment by amitkgupta** [comment]
Hi @camilamacedo86, did this issue get resolved? What is the next step?

**Comment by camilamacedo86** [comment]
It is solved now.
The versions were removed from the previous indexes and the OCP labels were updated in the repo to match with the config. See: https://github.com/redhat-openshift-ecosystem/certified-operators/pull/685/files
